version: '3'

services: 
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    container_name: 'selenoid'
    ports:
      - 4444:4444
    volumes:
      # if linux
      - $PWD/src/config/:/etc/selenoid/
      # if Windows
      # - C:\Users\Professional\Desktop\wdio-test\src\config\:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-service-startup-timeout", "1m", "-limit", "25", "-container-network", "selenoid"]

  # selenoid_ui:
  #   networks:
  #     selenoid: null
  #   image: aerokube/selenoid-ui
  #   container_name: 'selenoid-ui'
  #   depends_on: 
  #     - selenoid
  #   links:
  #     - selenoid
  #   ports:
  #     - 8082:8080
  #   command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    networks:
      selenoid: null
    image: tests:latest
    container_name: tests
    depends_on: 
        - selenoid
    volumes:
      - /allure-results:/usr/automation/allure-results
    environment:
      SELENIUM_HOST: selenoid
      SELENIUM_PORT: 4444
      # APP_URL:
      # API_URL:
      
networks:
  selenoid:
    external:
      name: selenoid