version: '3'

services:
    selenoid:
        networks:
            selenoid: null
        image: aerokube/selenoid:latest-release
        container_name: 'selenoid'
        ports:
            - 4444:4444
        volumes:
            - $PWD/src/config/:/etc/selenoid/
            - /var/run/docker.sock:/var/run/docker.sock
        command: ['-service-startup-timeout', '1m', '-limit', '25', '-container-network', 'selenoid']

    # image with tests - should be previously built
    tests:
        networks:
            selenoid: null
        image: tests:latest
        container_name: tests
        depends_on:
            - selenoid
        #volumes:
        # - /allure-results:/usr/automation/allure-results
        environment:
            SELENIUM_HOST: selenoid
            SELENIUM_PORT: 4444
            APP_URL: http://46.101.234.121

networks:
    selenoid:
        external:
            name: selenoid
