name: WebdriverIO UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:          
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: copy repository
        uses: actions/checkout@v2
        with:
          ubmodules: 'true'
          token: ${{secrets.CI_PAT}}
      - name: start tests
        run: bash ./run.tests.sh