name: UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:          
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: copy repository
        uses: actions/checkout@v2
      - name: start tests
        run: sh run.tests.sh