name: WebdriverIO UI Tests

on: 
  push:
    branches-ignore:
      - "!master"
    
jobs:
  first-job:
    name: setup env
    runs-on: ubuntu-latest
    services:
      chrome:
        image: aerokube/selenoid:latest-release
    steps:
      - name: test
        run: ls
          
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    services:
      selenoid:
        image: aerokube/selenoid:latest-release
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /src/config:/etc/selenoid/
    steps:
      - name: copy
        uses: actions/checkout@v2
      - name: Print docker containers
        run: docker ps
      - name: print directory
        run: ls
      - name: Install Dependencies
        run: npm ci
      - name: run tests
        run: npm run test