name: WebdriverIO UI Tests

on: 
  push:
    branches-ignore:
      - "!master"

jobs:          
  tests:
    runs-on: ubuntu-latest
    services:
      selenoid:
        image: selenium/node-chrome
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - 4444:4444
    steps:
      - name: ps
        run: docker ps
      - name: check
        run: java --version
      - name: copy
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: run tests
        run: npm run test:remote