name: UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:          
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: copy repository
        uses: actions/checkout@v2
      - name: create network
        run: docker network create -d bridge selenoid
      - name: pull chrome image
        run: docker pull selenoid/chrome:86.0
      - name: run tests
        run: docker-compose up