name: WebdriverIO UI Tests

on: 
  push:
    branches-ignore:
      - "!master"

jobs:          
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: copy
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: run tests
        run: npm run test