name: WebdriverIO UI Tests

on: 
  push:
    branches-ignore:
      - "!master"

jobs:          
  tests:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenoid/chrome:83.0

      selenoid:
        image: aerokube/selenoid:latest-release
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - src/config/:/etc/selenoid/
        ports:
          - 4444:4444
    steps:
      - name: ps
        run: docker ps -a
      - name: copy
        uses: actions/checkout@v2
      - name: check
        run: lsof -i
      - name: Install Dependencies
        run: npm ci
      - name: run tests
        run: npm run test:remote