name: WebdriverIO UI Tests

on: 
  push:
    branches-ignore:
      - "!master"
    
jobs:
  selenoid-job:
    runs-on: ubuntu-latest
    steps:
      - name: copy 
        uses: actions/checkout@v2
    services: 
      selenoid:
        image: aerokube/selenoid:latest-release
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${PWD}/wdio-test/src/config/:/etc/selenoid/
  testjob:
    runs-on: ubuntu-latest
    needs: selenoid-job
    steps:
      - name: Print docker containers
        run: docker ps
      - name: Install Dependencies
        run: npm ci
      - name: run tests
        run: npm run test